#!/usr/bin/env bash
# Configures a web server with nginx listening on port 80 and 
# when queried on root shows a page with the strin "Holberton School"
apt-get update -y
apt-get install -y nginx
ufw allow 'Nginx HTTP'
service nginx start
echo "Hello World" > /var/www/html/index.nginx-debian.html
