#!/usr/bin/env bash
# Bash script that ping an IP address passed as an argument
# ping IP 5 times

s1="8.8.8.8"
if [ "si" eq 0 ]; then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping -c 5 "$1"
fi
