#!/usr/bin/env bash
# Print file informations


if [ -e school ]; then
	echo "school file exists"

	if [ -s school ]; then
		echo "school file is not empt"
	else
		echo "school file is empt"
	fi

	if [ -f school ]; then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
